-- ============================================================================
-- TABELA: mkt_wep.wep_cadastro
--
-- Cadastros da NOVA página de captação. Populada pela automação (webhook/n8n)
-- via service_role. Segue as convenções das tabelas irmãs (wep_checkout,
-- wep_vendas, wep_pesquisa): id inteiro auto, data/hora separados, UTMs em text.
--
-- OBS 1: `utm_campaing` mantém o typo proposital — é o mesmo nome usado em
--        wep_vendas, para os joins/consultas ficarem consistentes.
-- OBS 2: `created_at` não estava na lista pedida, mas TODAS as tabelas irmãs
--        têm (auditoria, preenchido sozinho). Se não quiser, remova a linha.
-- ============================================================================

create table if not exists mkt_wep.wep_cadastro (
  id             bigint generated by default as identity primary key,
  tag            text,
  data           date,
  hora           time,
  primeiro_nome  text,
  sobrenome      text,
  telefone       text,
  tel_8d         text,
  utm_campaing   text,   -- typo proposital (igual a wep_vendas)
  utm_term       text,
  utm_medium     text,
  utm_content    text,
  utm_source     text,
  utm_pagina     text,
  created_at     timestamptz not null default now()
);

-- Índices para os filtros do painel (tag + janela de datas), como nas outras.
create index if not exists idx_wep_cadastro_tag  on mkt_wep.wep_cadastro (tag);
create index if not exists idx_wep_cadastro_data on mkt_wep.wep_cadastro (data);

comment on table mkt_wep.wep_cadastro is
  'Cadastros da página de captação (nome/telefone + UTMs), por tag.';

-- Segurança: o 07_lock_anon.sql já revoga SELECT/INSERT futuros para
-- anon/authenticated (default privileges). Só a service_role (automação e
-- /api/dashboard) acessa. Se a automação inserir com a ANON key, será preciso
-- um grant/policy específico — hoje o padrão do projeto é inserir via service_role.
